dist: trusty
sudo: false
git:
  depth: false
env:
  global:
    - CC_TEST_REPORTER_ID=53eef44d00d3465aeaf806ea310cfc5497e7473d13ae05fbc753890c39712c60
addons:
  sonarcloud:
    organization: "lucacappelletti94-github"
    token:
      secure:  "Gqd1I8SJ8Mtn4ec5lR8+tr7Huabh043efif8hVd8iKCHQ8uT8F+MXhitgsT5VNbR8xa8xgBxkI0tpMutdK58UH+6q8Kb+NPT1Ar1pTTbtbfmCc8yDOeON4AXv42uWeU1uWhzUQcS0CHEqBZNc2JdxTy5GNMvT6+Tn+6iF61Lkt8c8Vu2E8mBOpLTDicmtzOPdAtidGQqB4B3gQ56HywrJ9ztrXLRHRLabo1/JvrwohgDHbTc3Mixd0gb2rOwHw4j078Ar9/ysm+GNY1/Iq6EjId3bk29F3I9qhkUnuJOfhPFbZcJpxV24p9jTY/Do/930HFVQedrRcn20sqSRNzyB0Smr3EKQw6NRQLKYDBr6XlTK7Eu+vPpOoxP54ixCry7oN8JGIBdW1UOcM0EATR3O/kzSa53zC4dG6nDSGWP4p9Gjun1nidUQR3eytJsHDl4S9n7Tmor0niAOzpRRW9DVJJhb/ScN/9y7Iaof8YfwJSopybOGhPjEovj8pKRl0b8aNSSOAgRBiWFFaSu6hwyLRAq5NuivHVwV21UAFiJJmJKFxdtEhQLP0kQ3kmpBtjHOe3Te6Xbh5mAatszHweGR7HvNe7FVu05ed5VS5Dv6c/jKZtCUhO+gCvk9QCX1NGjUV69DuAi320+ODz29ArOezhHkhelUj5C7HOBBxiWbTk="
language: python
python:
- '3.6'
install:
- pip install .[test]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=pyadigraph --cov-report xml:coverage.xml 
#- coverage combine --append
- coverage report
- coverage xml
- sonar-scanner

after_success:
  - coveralls

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  email: false
