dist: trusty
sudo: false
git:
  depth: false
env:
  global:
    - CC_TEST_REPORTER_ID=53eef44d00d3465aeaf806ea310cfc5497e7473d13ae05fbc753890c39712c60
addons:
  sonarcloud:
    organization: "lucacappelletti94-github"
    token:
      secure:  "eP3X4s7agjtUPtSTULGlYSBoVC3311V76c1tfCxmZI7UQhBUCY+haV2mlQmMlCtpMQeeEz1NmPML8SaLiZJ8Mx1DKdHayjZ1KjV8KO7KfEzXlafbqhrbBKhZMUK7ZFknNZfRfbJsgDZRVCkwj96VhATNw1HkyYIdEvnzQvraCvdJxyqKl2H/IbFGV6hKpZF47pJARC6xSN4KG1vhWsA16whoPwsSS9FSrsewAfAW9C8cRYNs2XB52b5aQQx9ziW2dzUmgHFHfX57onI/TKjdgX5y1HOdQVOlj8eT3uyV/dNMy7t9wqLwhn7FK3JIi7GfuwX47H/bqZcQpzloYVdvXrUoB8YXN+O17e+IbLTzv7AsgKbMjVXttKsgPvrUE7tUUJQy8CO+9om6ptQzsThTFBOucabBAq9xrho3IZjBvXsGWyTMhSWWRi0CTdU1aj6zqqBnaN4GWwuA8kGhXWs8Kpf05xyl1YJEWQd4WSka1PxBooI9+WRPHWD7++wdpJ3M6IUN9SXzqo1PUhE0qEhlBao7H27ReEHuLoaDYQpDXczVoLVMYHYSpo/OOruyt3VJi95eKSASHWl7jSOe+7oFvUWIiv6dxdZ8BskbhCmtHbgOP2+suO0t0CjeA0s8sQtq1EGuUZLbu7TbNg5igLc9lb7j/+msowVTU2TkqBISkl4="
language: python
python:
- '3.6'
install:
- pip install .[test]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=pyadigraph --cov-report xml:coverage.xml 
#- coverage combine --append
- coverage report
- coverage xml
- sonar-scanner

after_success:
  - coveralls

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  email: false
